language: ruby
dist: trusty
sudo: false
cache: bundler
bundler_args: --without console tools
script:
  - bundle exec rake spec
before_install:
  - gem update --system
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.13.7
after_success:
  # Send coverage report from the job #1 == current MRI release
  - '[ "${TRAVIS_JOB_NUMBER#*.}" = "1" ] && [ "$TRAVIS_BRANCH" = "master" ] && bundle exec codeclimate-test-reporter'
rvm:
  - 2.3.2
  - 2.2
  - 2.1
  - jruby-9.1.5.0
  - ruby-head
  - rbx-3
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-3
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
